import type { QRPoint } from '../../types/QRPoint';

/**
 * Coordenadas x, y são relativas à imagem (0–100%, percentual).
 * 3 a 5 QR points por máquina para mock.
 */
export const qrpointsMock: QRPoint[] = [
  // Máquina 1 — Corte 01 (5 pontos)
  {
    id: 1,
    maquinaId: 1,
    x: 15,
    y: 18,
    codigo: 'QR-001',
    descricao: 'Motor principal',
    tipo: 'motor',
    status: 'atencao',
    healthScore: 72,
    ultimaInspecao: '10/03',
    proximaManutencao: '20/03',
    alertas: ['Vibração acima do ideal', 'Temperatura oscilando'],
  },
  {
    id: 2,
    maquinaId: 1,
    x: 48,
    y: 22,
    codigo: 'QR-002',
    descricao: 'Sensor lateral',
    tipo: 'sensor',
    status: 'ok',
    healthScore: 88,
    ultimaInspecao: '08/03',
    proximaManutencao: '22/03',
    alertas: [],
  },
  {
    id: 3,
    maquinaId: 1,
    x: 78,
    y: 35,
    codigo: 'QR-003',
    descricao: 'Painel elétrico',
    tipo: 'painel',
    status: 'ok',
    healthScore: 95,
    ultimaInspecao: '09/03',
    proximaManutencao: '25/03',
    alertas: ['Checar disjuntores'],
  },
  {
    id: 4,
    maquinaId: 1,
    x: 25,
    y: 55,
    codigo: 'QR-004',
    descricao: 'Área de corte',
    tipo: 'estrutura',
    status: 'ok',
    healthScore: 90,
    ultimaInspecao: '07/03',
    proximaManutencao: '21/03',
    alertas: [],
  },
  {
    id: 5,
    maquinaId: 1,
    x: 70,
    y: 60,
    codigo: 'QR-005',
    descricao: 'Comando manual',
    tipo: 'atuador',
    status: 'atencao',
    healthScore: 78,
    ultimaInspecao: '06/03',
    proximaManutencao: '19/03',
    alertas: ['Botão de emergência com jogo'],
  },
  // Máquina 2 — Costura 02 (4 pontos)
  {
    id: 6,
    maquinaId: 2,
    x: 12,
    y: 25,
    codigo: 'QR-001',
    descricao: 'Motor principal',
    tipo: 'motor',
    status: 'ok',
    healthScore: 93,
    ultimaInspecao: '09/03',
    proximaManutencao: '19/03',
    alertas: [],
  },
  {
    id: 7,
    maquinaId: 2,
    x: 45,
    y: 30,
    codigo: 'QR-002',
    descricao: 'Agulha',
    tipo: 'sensor',
    status: 'atencao',
    healthScore: 80,
    ultimaInspecao: '05/03',
    proximaManutencao: '18/03',
    alertas: ['Desgaste acima do esperado'],
  },
  {
    id: 8,
    maquinaId: 2,
    x: 75,
    y: 28,
    codigo: 'QR-003',
    descricao: 'Bobina',
    tipo: 'painel',
    status: 'ok',
    healthScore: 97,
    ultimaInspecao: '10/03',
    proximaManutencao: '24/03',
    alertas: [],
  },
  {
    id: 9,
    maquinaId: 2,
    x: 50,
    y: 65,
    codigo: 'QR-004',
    descricao: 'Painel elétrico',
    tipo: 'painel',
    status: 'falha',
    healthScore: 54,
    ultimaInspecao: '08/03',
    proximaManutencao: '23/03',
    alertas: ['Ruído intermitente em contato'],
  },
  // Máquina 3 — Montagem 03 (3 pontos)
  {
    id: 10,
    maquinaId: 3,
    x: 20,
    y: 35,
    codigo: 'QR-001',
    descricao: 'Motor principal',
    tipo: 'motor',
    status: 'ok',
    healthScore: 91,
    ultimaInspecao: '09/03',
    proximaManutencao: '21/03',
    alertas: [],
  },
  {
    id: 11,
    maquinaId: 3,
    x: 55,
    y: 40,
    codigo: 'QR-002',
    descricao: 'Sensor lateral',
    tipo: 'sensor',
    status: 'atencao',
    healthScore: 82,
    ultimaInspecao: '07/03',
    proximaManutencao: '20/03',
    alertas: ['Calibração recomendada'],
  },
  {
    id: 12,
    maquinaId: 3,
    x: 80,
    y: 55,
    codigo: 'QR-003',
    descricao: 'Painel elétrico',
    tipo: 'painel',
    status: 'ok',
    healthScore: 94,
    ultimaInspecao: '10/03',
    proximaManutencao: '26/03',
    alertas: [],
  },
];
